services:
  postgres:
    image: postgres
    container_name: product_db
    restart: always
    env_file:
      - product-service/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: product_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  notification-service:
    env_file:
      - notification-service/.env
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  product-service:
    env_file:
      - product-service/.env
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"

volumes:
  postgres_data: