services:
  postgres:
    image: postgres
    container_name: product_db
    restart: always
    env_file:
      - product-service/.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: product_service


  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"